"""add venue domain and ssl_enabled, portal_templates

Revision ID: 07eb9f30f838
Revises: eb99e7f3aac4
Create Date: 2026-02-14 13:32:39.598897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07eb9f30f838'
down_revision = 'eb99e7f3aac4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_templates',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('css_files', sa.JSON(), nullable=True),
    sa.Column('js_files', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_templates_id'), 'portal_templates', ['id'], unique=False)
    op.drop_index('netflow_records_time_idx', table_name='netflow_records')
    op.add_column('venues', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('ssl_enabled', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'venues', ['domain'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='unique')
    op.drop_column('venues', 'ssl_enabled')
    op.drop_column('venues', 'domain')
    op.create_index('netflow_records_time_idx', 'netflow_records', [sa.text('time DESC')], unique=False)
    op.drop_index(op.f('ix_portal_templates_id'), table_name='portal_templates')
    op.drop_table('portal_templates')
    # ### end Alembic commands ###
