"""add social actions tables

Revision ID: 222a84f3f24b
Revises: f17b29f6df9c
Create Date: 2026-02-19 20:13:10.200811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222a84f3f24b'
down_revision = 'f17b29f6df9c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_actions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('LIKE', 'SHARE', 'SUBSCRIBE', 'FOLLOW', name='socialactiontype'), nullable=False),
    sa.Column('network', sa.Enum('VK', 'TELEGRAM', 'INSTAGRAM', 'FACEBOOK', 'VIBER', name='socialnetwork'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_actions_id'), 'social_actions', ['id'], unique=False)
    op.create_table('venue_social_actions',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('reward_tariff_id', sa.Integer(), nullable=True),
    sa.Column('reward_duration_hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['social_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reward_tariff_id'], ['tariff_plans.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_social_actions_id'), 'venue_social_actions', ['id'], unique=False)
    op.create_table('user_social_actions',
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reward_tariff_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['social_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reward_tariff_id'], ['tariff_plans.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_social_actions_id'), 'user_social_actions', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_social_actions_id'), table_name='user_social_actions')
    op.drop_table('user_social_actions')
    op.drop_index(op.f('ix_venue_social_actions_id'), table_name='venue_social_actions')
    op.drop_table('venue_social_actions')
    op.drop_index(op.f('ix_social_actions_id'), table_name='social_actions')
    op.drop_table('social_actions')
    # ### end Alembic commands ###
