"""make banner image_url nullable

Revision ID: 278cd52919b8
Revises: 8704bbd6caf5
Create Date: 2026-02-15 19:39:28.697439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278cd52919b8'
down_revision = '8704bbd6caf5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banners', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banners', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
