"""add config to nas_devices

Revision ID: 6bfafcee1360
Revises: 34e418709a70
Create Date: 2026-02-16 10:15:44.599208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfafcee1360'
down_revision = '34e418709a70'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nas_devices', sa.Column('config', sa.JSON(), nullable=True))
    op.drop_index('idx_nas_devices_ip_unique_active', table_name='nas_devices', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('sms_providers', 'config',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='config::json')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_providers', 'config',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False,
               postgresql_using='config::text')
    op.create_index('idx_nas_devices_ip_unique_active', 'nas_devices', ['ip_address'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_column('nas_devices', 'config')
    # ### end Alembic commands ###